# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a06b27ca99ce82f084ba0aab0ef1c521206a8193e14b7d18bde6a350b75c12a0be6198b4e5a7d542edada25e9066eeaa435295766016db51fda68fd31c40d7a

test:
  secret_key_base: 1928466ef4fbda40983dffe95c2c21f99e97f7d56f84935f03286a4f8acea8f238e5850c633a003627fad79e72e1c924a6ab791176f4f162f066945b281930dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
